apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
    spec:
      containers:
      - name: crewpicker
        image: {{ .Values.container.image }}
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}
        env:
        - name: CREWPICKER_INSTANCE
          value: {{ .Release.Name }}
