apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Release.Name }}
    networking.gke.io/managed-certificates: {{ .Release.Name }}
    kubernetes.io/ingress.class: "gce"
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ include "hostname" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 80
